#!/usr/bin/env bash
# this script gives you information about these school file
# Your Bash script should check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is no empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)
		  
FILE="school"
if [ -e $FILE ];then
    echo "$FILE school file exists"

    if [ -s $FILE ]; then
	echo "$FILE school file is not empty"
    else
	echo "$FILE school file is empty"
    fi

    if [ -f $FILE ]; then
	echo "$FILE school file is a regular file"
    fi

else
    echo "$FILE school file does not exist"

fi
